### ISSUE TITLE
Unhandled AccessViolationException crashes Visual Studio

### ISSUE THREAD

**Issue by martinskuta** [laurentkempe/GitDiffMargin#135] opened 2017-10-19 14:16 UTC
Cannot really reproduce as the issue seems random, but it happens most of the time when visual studio is idle. Last time it crashed when I had just VS opened with a document with some changes and I locked PC for 5 minutes and when I came back unlocked pc and activated VS it crashed with the error log below, but it seems not really related to any specific action it crashed once just while working within VS with same error.

I am using GitDiffMargin 3.5.2.54 installed from VS marketplace running in VS 2017 version 15.4.0.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at LibGit2Sharp.Core.NativeMethods.git_status_file(LibGit2Sharp.FileStatus ByRef, LibGit2Sharp.Core.git_repository*, LibGit2Sharp.Core.FilePath)
   at LibGit2Sharp.Core.Proxy.git_status_file(LibGit2Sharp.Core.Handles.RepositoryHandle, LibGit2Sharp.Core.FilePath)
   at LibGit2Sharp.Repository.RetrieveStatus(System.String)
   at GitDiffMargin.Git.GitCommands+<GetGitDiffFor>d__3.MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToList[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at GitDiffMargin.Core.DiffUpdateBackgroundParser.ReParseImpl()
   at GitDiffMargin.Core.BackgroundParser.ReParse()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by laurentkempe** [comment] 2017-10-20 05:29
Thanks @martinskuta for the issue logging I will update to LibGit2Sharp 0.24.0 and LibGit2Sharp.NativeBinaries 1.0.185 and provide you a version to install so that you can try to see if the issue is fixed with those updates

**Comment by laurentkempe** [comment] 2017-10-20 05:39
Please @martinskuta, could you uninstall the current version you are using from Visual Studio.
Then, download the file in this comment, rename it to GitDiffMargin.vsix and double click it to install GitDiffMargin with the updated LibGit2Sharp.
[GitDiffMargin.vsix.zip](https://github.com/laurentkempe/GitDiffMargin/files/1400856/GitDiffMargin.vsix.zip)

Finally let me know if it solves the issue.
Thanks a lot.

**Comment by laurentkempe** [comment] 2017-10-20 08:51
Here is another one with a new GitDiffMargin version so that VS doesn't update it with the one from their servers [GitDiffMargin.vsix.zip](https://github.com/laurentkempe/GitDiffMargin/files/1401289/GitDiffMargin.vsix.zip)

**Comment by martinskuta** [comment] 2017-10-20 09:09
Now I get BadImageFormatException everytime. Wrong version of library? x64 instead of x86?

**Comment by laurentkempe** [comment] 2017-10-20 09:11
> x64 instead of x86?

Exactly! 😢 I re-created one and changed it in the [previous comment](https://github.com/laurentkempe/GitDiffMargin/issues/135#issuecomment-338147077)

**Comment by laurentkempe** [comment] 2017-10-20 11:34
Let's hope that one works for you finally because I didn't had any crash here - [GitDiffMargin.vsix.zip](https://github.com/laurentkempe/GitDiffMargin/files/1401775/GitDiffMargin.vsix.zip)

**Closed** 2017-10-20 18:48 UTC
