### ISSUE TITLE
Fix issue to upload on the marketplace

### ISSUE THREAD

**Issue by laurentkempe** [laurentkempe/GitDiffMargin#111] opened 2017-01-11 13:44 UTC
"This extension targets Visual Studio 2017 but was not built with an up-to-date VSSDK. Please make sure to update your references and try uploading again. Note: you'll also need to add Prerequisites to your extension.vsixmanifest."

**Comment by sharwell** [comment] 2017-01-12 12:13
I would call this a duplicate of #101.

**Comment by laurentkempe** [comment] 2017-01-13 05:28
@sharwell #114 fixes the upload on the marketplace! I did not go to the end of the process cause I still have one question concerning installation targets!

**Closed** 2017-01-14 12:16 UTC
