### ISSUE TITLE
With 3.1.1 use of memory of VS2013 increased until crashing - disabling helps

### ISSUE THREAD

**Issue by MartinL0815** [laurentkempe/GitDiffMargin#93] opened 2016-03-30 08:37 UTC
After the last update to 3.1.1 via the VS2013 extension update mechanism, I have the issue, that while working the memory consumption of VS2013 increases that much, that ...

1. in 5 Minutes 1GB is needed - instead of 500 to 800MB
2. in 10 Minutes 1.5GB
3. in 20 Minutes 2 GB
4. … VS2013 mostly crashes needing more than 2.8GB after becomming unresponsive

Disabling the extension stops this massive memory consumption!

I use TortoiseGIT 2.+.
Is something incompatible with the related libraries?

**Comment by laurentkempe** [comment] 2016-03-30 13:20
@MartinL0815 Thanks for the report I will have a look asap

**Comment by laurentkempe** [comment] 2016-04-04 06:33
@MartinL0815 I can't reproduce that with VS2015! Please in the meantime you can [downgrade to 3.1.0](https://github.com/laurentkempe/GitDiffMargin/releases/tag/v3.1.0)

**Comment by MartinL0815** [comment] 2016-04-04 07:29
Hi Laurent,

I had the problem in VS2013.

I'll update to 3.1.0 and try out, if the memory consumption is still so high!

Cheers,

Martin Lemburg
Berlin / Germany

martin.lemburg@gmx.net
http://about.me/Martin0815


------- Original message -------

**Comment by MartinL0815** [comment] 2016-04-04 11:46
Hi Laurent,

I took a look at the 3.1.1.0 release:
>Fixes
Fix SQL Server Object Explorer issue #81
Fix Enabling GitDiffMargin kills Git Source Control Provider #85
Fix Memory corruption in underlying libgit2 native DLL #87

There haven't been much changes, that could cause memory issus, right?

So some questions, that came to my mind:
* Exchanging the underlying libraries (#87) helped for VS2015, am I right?
* Did any function/method in the used libraries change, so that memory is not freed anymore, that was freed in a previous version - by one of the libraries?
* Or is a function/method now expect the call to free returned memory, that was handled differently before?
* And is there a difference in a .NET object handling memory passed to a library or retrieved from a library between VS2013 and VS2015?

Best regards,

Martin

**Comment by laurentkempe** [comment] 2016-04-04 15:04
> There haven't been much changes, that could cause memory issus, right?

I updated libgit2 native DLL which might be the cause of the issue!

> Exchanging the underlying libraries (#87) helped for VS2015, am I right?

Doesn't seem that it helped. I don't have the issue here but some users reported crash issues.

> Did any function/method in the used libraries change, so that memory is not freed anymore, that was freed in a previous version - by one of the libraries?

I don't know, but it looks like

> Or is a function/method now expect the call to free returned memory, that was handled differently before?

As far as I know no

> And is there a difference in a .NET object handling memory passed to a library or retrieved from a library between VS2013 and VS2015?

No

**Comment by laurentkempe** [comment] 2016-04-15 14:07
@MartinL0815 I can see that now too here! It seems that it is due to the update of libgit2sharp and my usage of Diff because there are fixing lots of things in that area in their last commits! I reverted to 3.1.0 and do not see that problem at the moment anymore. I will update GitDiffMargin as soon as the new libgit2sharp is released

**Comment by laurentkempe** [comment] 2016-04-15 22:35
@MartinL0815 I just created a temporary pre-release [here](https://github.com/laurentkempe/GitDiffMargin/releases/tag/untagged-606149f93bd0bc8977db) of 3.1.2 which included latest libgit2sharp.
Would it be possible for you to install it, try it and give feedback please, thanks!

**Comment by MartinL0815** [comment] 2016-04-16 10:18
I'll check it out at Monday!

**Comment by laurentkempe** [comment] 2016-04-16 10:19
@MartinL0815 Great thanks a lot! Have a nice weekend

**Comment by laurentkempe** [comment] 2016-04-19 11:02
@MartinL0815 Any news?

**Comment by MartinL0815** [comment] 2016-04-19 11:12
Sorry @laurentkempe!

Was too busy, since my office workstation got screwed "a bit" after an office software deployment!

I forgot to ask … where do I get the 3.1.2 preview-release from to test with?

**Comment by laurentkempe** [comment] 2016-04-19 13:37
[Here](https://github.com/laurentkempe/GitDiffMargin/releases/tag/untagged-606149f93bd0bc8977db) as stated in the [previous comment](https://github.com/laurentkempe/GitDiffMargin/issues/93#issuecomment-210671238) It is a build especially for you :smiley:

**Comment by MartinL0815** [comment] 2016-04-19 13:59
Sorry - 404 
![image](https://cloud.githubusercontent.com/assets/525700/14641655/a6dcf452-0647-11e6-9c27-123c3c723350.png) - so not "here"! ;)

**Comment by MartinL0815** [comment] 2016-04-19 14:00
Since I need a kind of high-contrast-mode, I use extensions to enhance the contrast of web pages. The "here" link is difficult to recognize, so I have overseen it!
And now ... 404.

**Comment by laurentkempe** [comment] 2016-04-19 14:02
Ok you didn't had access to Draft release, now you should https://github.com/laurentkempe/GitDiffMargin/releases/tag/v3.1.2

**Comment by MartinL0815** [comment] 2016-04-20 11:54
So - after working ca. a day with the pre-release 3.1.2, I'd say: everything is fine!

**Comment by laurentkempe** [comment] 2016-04-20 11:57
Thanks a lot @MartinL0815 for reporting this and for the time to test the pre-release of 3.1.2, very much appreciated :+1:  

I will get back to the LibGit2Sharp with this feedback. cc @ethomson

**Comment by ethomson** [comment] 2016-04-20 11:59
Great news.  Sorry for the inconvenience!

**Comment by laurentkempe** [comment] 2016-04-20 12:02
@ethomson Yep that's a great news, now the question is when will we get a new release of LibGit2Sharp as v0.22 is buggy?

**Comment by laurentkempe** [comment] 2016-04-28 20:13
Fixed with 3.1.2

**Closed by laurentkempe** 2016-04-28 20:13 UTC
