### ISSUE TITLE
Keyboard shortcuts for GitDiffMargin.NextChange & GitDiffMarginPreviousChange don't work

### ISSUE THREAD

**Issue by Jeff-Hewlett** [laurentkempe/GitDiffMargin#658] opened 2022-07-22 07:15 UTC
## Versions
 - Git Diff Margin version: 3.12.1
 - Visual Studio version: VS 2019 and VS 2022

## What happened
The setting for the keyboard shortcuts for the extension can be seen on the Options->Environment->Keyboard. After assigning any shortcut to them, the shortcut still doesn't work. Nothing happened like nothing changed.

### Additional context
I found the extension is quite useful. If the bug can be fixed, it will be really appreciated. 
Thank you.

**Comment by maciey** [comment] 2022-08-26 07:57
+1 
Same here. I noticed all Git Margin toolbar commands are greyed out - maybe this is related

Jumping to next change in file is key to me - appreciate if this can be fixed :)

![obraz](https://user-images.githubusercontent.com/5410448/186852436-7121a186-0014-406b-ad87-7c4e6cf6d70d.png)

**Comment by laurentkempe** [comment] 2022-08-29 16:13
@Jeff-Hewlett Thanks for the report, this is a duplicate of #542 
@maciey The toolbar is not supposed to be used, you should use the the thing on the margin! As you can read on #542 

I will close that issue as it is already described and discussed on the other one!

**Closed as completed by laurentkempe** 2022-08-29 16:13 UTC
Labels: bug
